version: "3.8"

services:

  nginx-gateway:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - api-service

  api-service:
    build: ./api-service
    ports:
      - "3000:3000"
    environment:
      DB_HOST: postgres-db
      DB_NAME: crud_db
      DB_USER: postgres
      DB_PASS: postgres
    depends_on:
      - postgres-db
    expose:
      - "3000"  # Nginx accede internamente

  postgres-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: crud_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
